- name: Configuración común para todos los servidores
  hosts: all
  become: yes
  tasks:
    - name: Configurar zona horaria
      timezone:
        name: "{{ timezone }}"

    - name: Configurar locale
      locale_gen:
        name: "{{ locale }}"
        state: present

    - name: Actualizar todos los paquetes
      apt:
        update_cache: yes
        upgrade: yes
        
    - name: Instalar paquetes esenciales
      apt:
        name:
          - vim
          - curl
          - wget
          - htop
          - net-tools
          - ufw
          - fail2ban
          - python3-pip
        state: present

    - name: Configurar UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "{{ ssh_port }}"
        - 80
        - 443

    - name: Habilitar UFW
      ufw:
        state: enabled
        policy: deny

    - name: Configurar fail2ban
      template:
        src: ../templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted
